#!/usr/bin/env bash
#
# build_portable.sh — build dist/human-copywrite-portable.md, a single-file
# version of the skill for models and apps that take one system prompt
# instead of a skill folder: ChatGPT (Projects / custom GPTs), Gemini (Gems),
# GLM, DeepSeek, Kimi, or any OpenAI-compatible API.
#
# It concatenates SKILL.md (frontmatter stripped) with the core references,
# and rewrites the "load references/x.md" framing into "see the section
# below", since everything ships in one file.

set -euo pipefail

SKILL_DIR="human-copywrite"
DIST_DIR="dist"
OUTPUT="${DIST_DIR}/human-copywrite-portable.md"

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT}"

if [[ ! -f "${SKILL_DIR}/SKILL.md" ]]; then
  echo "error: ${SKILL_DIR}/SKILL.md not found. Run from the repository root." >&2
  exit 1
fi

mkdir -p "${DIST_DIR}"

{
  echo "<!-- human-copywrite portable build. Generated by scripts/build_portable.sh; do not edit by hand."
  echo "     Single-file version for system-prompt use (ChatGPT, Gemini, GLM, DeepSeek, Kimi, and any"
  echo "     OpenAI-compatible API). The referenced files are appended below as sections. -->"
  echo
  # SKILL.md body without the YAML frontmatter block.
  awk 'BEGIN{fm=0} /^---$/{fm++; next} fm!=1{print}' "${SKILL_DIR}/SKILL.md"
  echo
  for ref in process-bleed website-copy substance integrity ai-tells voice-calibration voice-setup; do
    echo
    echo "---"
    echo
    echo "<!-- appended from references/${ref}.md -->"
    echo
    cat "${SKILL_DIR}/references/${ref}.md"
  done
  echo
  echo "---"
  echo
  echo "Portable-build notes: every \`references/<name>.md\` mentioned above is included in this file as a section; read the section instead of loading a file. The \`scripts/copy_scan.py\` scanner and the QA scorecard and Hungarian translation handoff are only in the full skill package. Without a filesystem, deliver MY_OWN_VOICE.md as a code block for the user to save and paste back in future sessions."
} > "${OUTPUT}"

echo "Built ${OUTPUT} ($(wc -c < "${OUTPUT}") bytes)"
